" Vundle config - DO NOT TOUCH
set shell=/bin/bash
set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()
" Bundle 'gmarik/vundle'

" Bundle help
" The following are examples of different formats supported.
" Keep bundle commands between here and filetype plugin indent on.
" scripts on GitHub repos
" Bundle 'tpope/vim-fugitive'
" Bundle 'Lokaltog/vim-easymotion'
" Bundle 'tpope/vim-rails.git'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
" scripts from http://vim-scripts.org/vim/scripts.html
Bundle 'L9'
Bundle 'FuzzyFinder'

" scripts not on GitHub
" Bundle 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Bundle 'file:///home/gmarik/path/to/plugin'
" ...
"---------------------------------------------------------------------------------------------
" My Bundles
Bundle 'Raimondi/delimitMate'
Bundle 'Valloric/YouCompleteMe'
"Bundle 'scrooloose/syntastic'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
    autocmd VimEnter * NERDTree
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
Bundle 'majutsushi/tagbar'
Bundle 'oblitum/rainbow'
Bundle 'bling/vim-airline'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#fnamemod = ':t'
Bundle 'airblade/vim-gitgutter'
Bundle 'SirVer/ultisnips'
Bundle 'flazz/vim-colorschemes'
"Bundle 'edkolev/promptline.vim'
Bundle 'honza/vim-snippets'


filetype plugin indent on     " required

"----------------------------------------------------------------------------------------------
" REAL VIMRC STARTS HERE
set encoding=utf-8     "Set encoding
set hidden             "Better buffer behavior

" Look and feel
set number
set ruler

set laststatus=2       " Status bar

let g:ycm_autoclose_preview_window_after_completion = 1
"let g:ycm_global_ycm_extra_conf = '$HOME/.vim/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 1 "change to 0

" Whitespace stuff
set nowrap
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set list listchars=tab:\ \ ,trail:·

" Remove all trailing whitespace
autocmd FileType c,cpp,php,rb,py,js,html autocmd BufWritePre * :%s/\s\+$//e

" Smoother scrolling
set scrolloff=3
nnoremap <Space> <C-d>

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Load the plugin and indent settings for the detected filetype
set autoindent
set smartindent
filetype plugin indent on

" Show (partial) command in the status line
set showcmd

"Solarized shit
let g:solarized_termcolors=256
set t_Co=256
syntax enable
set background=dark
colorscheme molokai
" Cpp mappings and other
map <F2> :w <CR>
imap <F2> <ESC> :w <CR>
set makeprg=g++\ -Wall\ -std=c++0x\ -Wextra\ -W\ -Wno-return-type\ -Wformat\ -g\ %\ -o\ %<
map <F3> :make <CR>
imap <F3> <ESC> :make <CR>
map <F4> :q <CR>
imap <F4> <ESC> :q <CR>
map <F5> :vsp %<t <CR>
imap <F5> <ESC> :vsp %<t <CR>
map <F6> :!./%< <CR>
imap <F6> <ESC>:!./%< <CR>
map <F7> :!gdb  %< <CR>
imap <F7> <ESC>:!gdb %< <CR>
map <F8> :!./%< < %<t <CR>
imap <F8> <ESC>:!./%< < %<t <CR>
nnoremap <Leader>jd :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <Leader>f :FufFile <CR>
:command Cpp r ~/Dropbox/c++/CONTEST_LIBRARY/oldtemplate.cpp
:command Cpp11 r ~/Dropbox/c++/CONTEST_LIBRARY/template.cpp
:command Tex r ~/Dropbox/Dokumenty/TeX/template.tex
:command Py !python %
:command Pdf !pdflatex %
:command Build !g++ -Wall -Wextra -W -Wformat -g % -o %<
let loaded_matchparen = 1
autocmd VimEnter * AirlineTheme zenburn
map <F9> :bprev <CR>
map <F10> :bnext <CR>
:set guioptions-=m  "remove menu bar
:set guioptions-=T  "remove toolbar
:set guioptions-=r  "remove right-hand scroll bar
:set guioptions-=L  "remove left-hand scroll bar

let g:ConqueTerm_TERM = 'xterm-256color'
let g:ConqueTerm_Color = 1



"they say it fixes ultisnips problem
function! g:UltiSnips_Complete()
    call UltiSnips#ExpandSnippet()
    if g:ulti_expand_res == 0
        if pumvisible()
            return "\<C-n>"
        else
            call UltiSnips#JumpForwards()
            if g:ulti_jump_forwards_res == 0
               return "\<TAB>"
            endif
        endif
    endif
    return ""
endfunction

au BufEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsListSnippets="<c-e>"
" this mapping Enter key to <C-y> to chose the current highlight item
" and close the selection list, same as other IDEs.
" CONFLICT with some plugins like tpope/Endwise
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

autocmd BufEnter * RainbowLoad
:set mouse=a
