# Initialize colors.
autoload -U colors
colors

# Autoload zsh functions.
fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

. ~/.zsh/environment
. ~/.zsh/prompt
. ~/.zsh/colors
. ~/.zsh/completion
. ~/.zsh/bindings

. ~/.zshrc.local
export TERM=xterm-256color
source $HOME/.nvm/nvm.sh
nvm use v0.10.12


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
